apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
  annotations:
    github.com/project-slug: backstage-test-1/${{ values.name }}
    argocd/app-name: ${{ values.name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: experimental
  system: ${{ values.systemName }}
