apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.name }}
  {%- if values.description %}
  description: ${{ values.description | dump }}
  {%- endif %}
spec:
  owner: ${{ values.owner }}