apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.systemName }}-${{ values.name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/backstage-test-1/${{ values.systemName }}-${{ values.name }}
    targetRevision: main
    path: k8s
    directory:
      exclude: 'argocd-app.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.systemName }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
